# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 825)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1045, 825))
        MainWindow.setMaximumSize(QtCore.QSize(1045, 825))
        MainWindow.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(430, 10, 600, 450))
        self.Image.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"                                  border-style: outset;\n"
"                                  border-color: rgb(0, 0, 0);\n"
"                                  border-width: 5px;\n"
"                                  border-radius:15px;")
        self.Image.setText("")
        self.Image.setObjectName("Image")
        self.LL = QtWidgets.QLineEdit(self.centralwidget)
        self.LL.setGeometry(QtCore.QRect(10, 50, 391, 20))
        self.LL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LL.setObjectName("LL")
        self._label_cords = QtWidgets.QLabel(self.centralwidget)
        self._label_cords.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setFamily("SamsungOneUI Medium Condensed")
        font.setPointSize(14)
        self._label_cords.setFont(font)
        self._label_cords.setStyleSheet("color: rgb(255, 255, 255);")
        self._label_cords.setObjectName("_label_cords")
        self._label_ms = QtWidgets.QLabel(self.centralwidget)
        self._label_ms.setGeometry(QtCore.QRect(10, 90, 131, 16))
        font = QtGui.QFont()
        font.setFamily("SamsungOneUI Medium Condensed")
        font.setPointSize(14)
        self._label_ms.setFont(font)
        self._label_ms.setStyleSheet("color: rgb(255, 255, 255);")
        self._label_ms.setObjectName("_label_ms")
        self.Spn = QtWidgets.QLineEdit(self.centralwidget)
        self.Spn.setGeometry(QtCore.QRect(10, 120, 391, 20))
        self.Spn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Spn.setObjectName("Spn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LL.setText(_translate("MainWindow", "36.15,51.72"))
        self._label_cords.setText(_translate("MainWindow", "Координаты"))
        self._label_ms.setText(_translate("MainWindow", "Масштаб"))
        self.Spn.setText(_translate("MainWindow", "0.5,0.5"))
